title: SembleLang
email: draxdo@gmail.com
description: >-
  Duck typing. Faster than C.
  <h3><a href="https://semblelang.org">Home</a></h3>
  <h3><a href="/downloads.html">Downloads</a></h3>
  <h3><a href="/docs.html">Docs</a></h3>
#config
theme: jekyll-theme-minimal
© 2021 GitHub, Inc.
