title: Photography
email: yourname@example.com
description: >-
  Duck typing. Faster than C.
  <h3><a href="/index.html">Home</a></h3>
  <h3><a href="/gallery.html">Gallery</a></h3>
  <h3><a href="/about.html">About</a></h3>
#config
theme: jekyll-theme-midnight
